# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fexec < Formula
  desc "Connect to a container running on AWS Fargate."
  homepage ""
  version "0.5.2"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gajirou/fexec/releases/download/v0.5.2/fexec_darwin_amd64.tar.gz"
      sha256 "496cdd71c391f8fc67bb632368bdd029176820b7b300ad8a1a505010d047196d"

      def install
        bin.install "fexec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gajirou/fexec/releases/download/v0.5.2/fexec_darwin_arm64.tar.gz"
      sha256 "391a0d31d2a94f88bf07f432057da13807ad58d24d5849040bef72d6b6d7674b"

      def install
        bin.install "fexec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gajirou/fexec/releases/download/v0.5.2/fexec_linux_amd64.tar.gz"
      sha256 "cf392abae4927d2a057d425fdd93c251f613ac2810cdac843ddd427f6405d821"
      def install
        bin.install "fexec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gajirou/fexec/releases/download/v0.5.2/fexec_linux_arm64.tar.gz"
      sha256 "fcc2a4b2c48d66c6d491e041632d5f42ecb6b58069162af01f152ce70d9c29bb"
      def install
        bin.install "fexec"
      end
    end
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
