# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fexec < Formula
  desc "Connect to a container running on AWS Fargate."
  homepage ""
  version "0.1.14"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gajirou/fexec/releases/download/v0.1.14/fexec_macos_arm64.tar.gz"
      sha256 "1fd4f6ce64b556b0c30d2a62addcdeab0283af95889e11adb57613abec05bfee"

      def install
        bin.install "fexec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gajirou/fexec/releases/download/v0.1.14/fexec_macos_amd64.tar.gz"
      sha256 "50964cbb4a66f51dcf59a968707ea22b30546462e5fb3813ccde434f25deba6c"

      def install
        bin.install "fexec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gajirou/fexec/releases/download/v0.1.14/fexec_linux_amd64.tar.gz"
      sha256 "41bd644378f71b03342a8de0ad2bfbe9afe9e8161bfdaf2521cb78e8c5bac43b"

      def install
        bin.install "fexec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gajirou/fexec/releases/download/v0.1.14/fexec_linux_arm64.tar.gz"
      sha256 "3fad341ab9d10cb345a418f24652ad8a104e8e3fafb7d43cae61daf32baff7bd"

      def install
        bin.install "fexec"
      end
    end
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
